<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="servicioConvenioWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/servicioConvenioWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/servicioConvenioWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://servicio/">
    <import location="http://localhost:9120/servicioconvenio/servicioConvenio?WSDL" namespace="http://servicio/"/>
    <plnk:partnerLinkType name="servicioConvenioLinkType">
        <plnk:role name="servicioConvenioRole" portType="ns:servicioConvenio"/>
    </plnk:partnerLinkType>
</definitions>
